
.cmake_tests:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  stage: test
  timeout: 2 hours
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    set -x
    git config --global --add safe.directory ${CI_PROJECT_DIR}/gyselalibxx/vendor/kokkos
    rm -rf build || true
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=${CI_PROJECT_DIR}/gyselalibxx/toolchains/${TOOLCHAIN} ..
    cmake --build . -j 4
    ctest -j 2 --timeout 5 --output-junit tests.xml --output-on-failure
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit: ./build/tests.xml


cmake_tests:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '0.0'
    ABSOLUTE_RESTART_TOLERANCE: '0.0'
    TOOLCHAIN: 'docker.gyselalibxx_env/tests_toolchain.cmake'

cmake_tests_Release:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '0.0'
    ABSOLUTE_RESTART_TOLERANCE: '0.0'
    TOOLCHAIN: 'docker.gyselalibxx_env/tests_release_toolchain.cmake'

cmake_tests_Release_OpenMP:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '0.0'
    ABSOLUTE_RESTART_TOLERANCE: '0.0'
    TOOLCHAIN: 'docker.gyselalibxx_env/tests_release_omp_toolchain.cmake'

cmake_tests_Release_GPU:
  extends: .cmake_tests
  tags:
    - persee
  variables:
    RELATIVE_RESTART_TOLERANCE: '1e-14'
    ABSOLUTE_RESTART_TOLERANCE: '1e-14'
    TOOLCHAIN: 'v100.persee/toolchain.cmake'
  before_script: |
    . ${CI_PROJECT_DIR}/gyselalibxx/toolchains/v100.persee/environment.sh

indentation:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    ./ci_tools/indent -td

python_best_practices:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    export PYTHONPATH="./post-process/PythonScripts"
  script: |
    pylint $(find tests -iname *.py)
    pylint $(find doc -iname *.py)
    pylint $(find ci_tools -iname *.py)
    # Find all files with no extension or a .py extension in post-process/PythonScripts/
    POST_PROCESS_PYTHON_FILES=$(find post-process/PythonScripts/ -type f ! -name "*.*"; find post-process/PythonScripts -iname *.py)
    # Get pylint errors without failing
    pylint ${POST_PROCESS_PYTHON_FILES} > post_process_errors.txt || true
    # Filter errors on changed files
    git config --global --add safe.directory $(pwd)
    git fetch origin main
    for f in $(git diff origin/main --name-only); do grep $f post_process_errors.txt || true; done | tee filtered_errors.txt
    # Raise an error if post-process in filtered errors
    ! grep "post-process" filtered_errors.txt >/dev/null

