
stages:
  - static_analysis
  - test

.cmake_tests:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  stage: test
  timeout: 2 hours
  needs: []
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    set -x
    git config --global --add safe.directory ${CI_PROJECT_DIR}/gyselalibxx/vendor/kokkos
    rm -rf build || true
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=${CI_PROJECT_DIR}/gyselalibxx/toolchains/${TOOLCHAIN} ..
    cmake --build . -j 4
    ctest -j 2 --timeout 5 --output-junit tests.xml --output-on-failure
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit: ./build/tests.xml


cmake_tests:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '0.0'
    ABSOLUTE_RESTART_TOLERANCE: '0.0'
    TOOLCHAIN: 'common_toolchains/serial_debug_toolchain.cmake'
    CMAKE_PREFIX_PATH: /opt/serial

cmake_tests_Release:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '0.0'
    ABSOLUTE_RESTART_TOLERANCE: '0.0'
    TOOLCHAIN: 'common_toolchains/serial_release_toolchain.cmake'
    CMAKE_PREFIX_PATH: /opt/serial

cmake_tests_Release_OpenMP:
  extends: .cmake_tests
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    RELATIVE_RESTART_TOLERANCE: '1e-14'
    ABSOLUTE_RESTART_TOLERANCE: '1e-14'
    TOOLCHAIN: 'common_toolchains/openmp_release_toolchain.cmake'
    CMAKE_PREFIX_PATH: /opt/openmp
  before_script: |
    . ${CI_PROJECT_DIR}/gyselalibxx/toolchains/docker.gyselalibxx_env/tests_omp_environment.sh

cmake_tests_Release_GPU:
  extends: .cmake_tests
  tags:
    - persee
  variables:
    RELATIVE_RESTART_TOLERANCE: '1e-14'
    ABSOLUTE_RESTART_TOLERANCE: '1e-14'
    TOOLCHAIN: 'persee/v100/toolchain.cmake'
  before_script: |
    . ${CI_PROJECT_DIR}/gyselalibxx/toolchains/persee/v100/environment.sh

indentation:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    ./ci_tools/indent -td

python_best_practices:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    # Find all files with a .py extension not in gyselalibxx
    PYTHON_FILES=$(find . -type f -name "*.py" ! -path "*/gyselalibxx/*")
    if [ -n "${PYTHON_FILES}" ]
    then
      pylint ${PYTHON_FILES}
    fi

documentation:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script: |
    git config --global --add safe.directory $CI_PROJECT_DIR
    git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} --recurse-submodules=no
    git config --global --add safe.directory ${CI_PROJECT_DIR}/gyselalibxx/vendor/kokkos
    pip install -r gyselalibxx/docs/requirements.txt
  script: |
    rm -rf docs/mkdoc docs/site || true
    python3 gyselalibxx/docs/prepare_mkdocs.py . docs/mkdoc gyselalibxx/ docs/mkdoc
    cd docs
    mkdocs build
    cat doxygen.log
    cd ..
    # Get files which have changed in this merge request
    git diff origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..HEAD --no-indent-heuristic --unified=0 --output=pull_new_files.txt --no-color --diff-filter=A
    if [ -s docs/doxygen.log ]; then exit 1; fi


cppcheck_static_analysis:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script: |
    git config --global --add safe.directory $(pwd)
    git fetch --no-recurse-submodules origin ${CI_MERGE_REQUEST_DIFF_BASE_SHA}
  script: |
    git diff --name-only ${CI_MERGE_REQUEST_DIFF_BASE_SHA} > changed_files.txt
    CHANGED_FILES=$(awk '{printf("%s ",$0)} END { printf "\n" }' changed_files.txt)
    set +e
    python3 gyselalibxx/bin/ci_tools/gyselalib_static_analysis.py ${CHANGED_FILES} --default-geometry=geometryXVx --home-dir=${CI_PROJECT_DIR}
  allow_failure:
    exit_codes: [1, 2] # Allow failure due to style or error but not fatal

markdown_best_practices:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  image: ghcr.io/gyselax/gyselalibxx_env
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: |
    MARKDOWN_FILES=$(find . -name "*.md" -not -path "./gyselalibxx/*")
    echo $MARKDOWN_FILES
    set +e
    python3 gyselalibxx/bin/ci_tools/markdown_linter.py ${MARKDOWN_FILES}
  allow_failure:
    exit_codes: 2

spelling:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: static_analysis
  needs: []
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script: |
    apt-get update -qy
    apt-get install -y wget
    mkdir typos
    cd typos
    wget -qO- https://github.com/crate-ci/typos/releases/download/v1.30.3/typos-v1.30.3-x86_64-unknown-linux-musl.tar.gz | gunzip | tar xvf -
    cd ..
  script: |
    cp gyselalibxx/.typos.toml .typos.toml
    ./typos/typos ./CMakeLists.txt ./ci_tools ./pre-process ./post-process ./README.md ./simulations ./src ./tests/
