#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
"""diagnostic of normalised density conservation equation:
    d(n)/dt + sqrt(m_e/m_i) d(n_eq u_i)/dx - alpha_0 d(D T_n d(n)/dx)/dx = S_n / alpha_0
    with alpha_0 = omega_pe0 / (n_0 k_0) the normalisation coefficient.
"""

from argparse import ArgumentParser
from pathlib import Path

import matplotlib.pyplot as plt

from gysdata_voice import DiskStore
from plot_utils import plot_field1d, plot_field2d
from math_utils import compute_moment, differentiate
from utils import compute_krook_neutrals

if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the density conservation equation error for neutrals')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-2,
                        type=int,
                        help='time index')
    parser.add_argument('--show',
                        action='store_true',
                        default=False,
                        help='Displays figures')
    parser.add_argument('--slice_begin',
                        action='store',
                        default=0,
                        type=float,
                        help='first point to consider (0,1)')
    parser.add_argument('--slice_end',
                        action='store',
                        default=1,
                        type=float,
                        help='first point to consider (0,1)')
    parser.add_argument('--with_mask',
                        action='store_true',
                        default=False,
                        help='Display the mask contribution')
    args = parser.parse_args()

    # Load data
    path_data_structure = Path('data_structure_neutral.yaml')
    ds = DiskStore(args.data_dir, data_structure=path_data_structure)

    fluid_moments = ds['fluid_moments']
    fdistribu = ds['fdistribu']
    current_nspecies = 'neutrals'
    diffusive_term = ds["diffusion_term"].sel(speciesn=current_nspecies)
    convective_term = ds["convection_term"].sel(speciesn=current_nspecies)
    k_cx = ds['charge_exchange_rate']
    k_r = ds['recombination_rate']
    k_i = ds['ionisation_rate']

    alpha_0 = ds['normalisation_coeff_neutrals']
    neutrals_mask = ds['krook_neutrals_mask']

    # Plasma density
    densities = compute_moment(fdistribu, 'v_x', moment_order=0)
    densities = densities.chunk({'time': len(densities['time'])})
    density_e = densities.sel(species='electrons')
    density_i = densities.sel(species='ions')

    # Neutral density
    moment_order = 'density'
    density_n = fluid_moments.sel(
        speciesn=current_nspecies, moment=moment_order)
    density_n = density_n.chunk({'time': len(density_n['time'])})

    # First term
    dn_dt = differentiate(density_n, 'time')

    # Second term, diffusive
    diffusive_term = diffusive_term*(1-neutrals_mask)

    # Third term, convective
    convective_term = convective_term*(1-neutrals_mask)
    # Fourth term, source
    S_n = density_i * density_e * k_r - density_n * density_e * k_i
    source_term = S_n / alpha_0
    source_term = source_term*(1-neutrals_mask)

    # Fifth term, neutral krook
    source_krook = -compute_krook_neutrals(ds)

    error = dn_dt + convective_term + diffusive_term - source_term - source_krook

    time_diag = fluid_moments.coords['time'].values[args.itime]
    time_init = fluid_moments.coords['time'].values[0]
    time_values = density_n.coords['time'].values
    dt = time_values[1] - time_values[0]
    idx = fluid_moments.coords['x'].values
    slice_left = args.slice_begin*idx[-1]
    slice_right = args.slice_end*idx[-1]
    title = f'density conservation equation error {current_nspecies}, x=({slice_left},{slice_right}), t={time_diag}, dt={dt}'

    output_filename = Path.cwd() / \
        f'density_conservation_error_{current_nspecies}_xt_dt{dt}.png'
    plot_field2d(error,
                 title,
                 output_filename,
                 scale='linear',
                 cmap='viridis')

    data_dict = {r'$\partial_t n_s$': dn_dt.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
                 r'$\sqrt{\frac{m_e}{m_i}} \partial_x (n_{eq} u_i)$': convective_term.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
                 r'$-\alpha_0 \partial_x (D T_n \partial_x n)$': diffusive_term.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
                 r'$\frac{S_n}{\alpha_0}$': source_term.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
                 r'$S_{krook}$': source_krook.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
                 r'lhs-rhs': error.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)]}

    output_filename = Path.cwd() / \
        f'density_conservation_error_{current_nspecies}_t{time_diag}_dt{dt}.png'
    plot_field1d(data_dict, title, output_filename)

    if args.show:
        plt.show()
