#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
"""diagnostic of reaction rates
    K_i, K_r and K_cx
"""

from argparse import ArgumentParser
from pathlib import Path

import matplotlib.pyplot as plt

from gysdata_voice import DiskStore
from plot_utils import plot_field1d

if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plot the reaction rates')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')
    parser.add_argument('--show',
                        action='store_true',
                        default=False,
                        help='Displays figures')
    parser.add_argument('--slice_begin',
                        action='store',
                        default=0,
                        type=float,
                        help='first point to consider (0,1)')
    parser.add_argument('--slice_end',
                        action='store',
                        default=1,
                        type=float,
                        help='first point to consider (0,1)')
    args = parser.parse_args()

    # Load data
    path_data_structure = Path('data_structure_neutral.yaml')
    ds = DiskStore(args.data_dir, data_structure=path_data_structure)
    k_cx = ds['charge_exchange_rate']
    k_r = ds['recombination_rate']
    k_i = ds['ionization_rate']

    idx = k_i.coords['x'].values
    idt = k_i.coords['time'].values
    slice_left = args.slice_begin*idx[-1]
    slice_right = args.slice_end*idx[-1]

    time_diag = k_cx.coords['time'].values[args.itime]
    time_init = k_cx.coords['time'].values[0]
    time_values = k_cx.coords['time'].values
    dt = time_values[1] - time_values[0]
    title = f'reaction rate, x=({slice_left},{slice_right}), t = {time_diag}, dt_diag={dt}'

    data_dict = {
        r'$K_{cx}$': k_cx.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
        r'$K_i$': k_i.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)],
        r'$K_r$': k_r.sel(time=time_diag)[(idx <= slice_right) & (idx >= slice_left)]
    }

    output_filename = Path.cwd() / \
        f'reaction_rate_t{time_diag}_dt{dt}.png'
    plot_field1d(data_dict, title, output_filename)
    output_filename = Path.cwd() / \
        f'reaction_rate_t{time_diag}_dt{dt}_log.png'
    plot_field1d(data_dict, title, output_filename, scale='log')

    if args.show:
        plt.show()
