#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import os

from argparse import ArgumentParser
from pathlib import Path

from gysdata_voice import DiskStore
from plot_utils import plot_field1d, plot_field2d
from math_utils import compute_moment
from utils import compute_fluid_velocity


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the plasma fluid velocity')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')
    parser.add_argument('--slice_begin',
                        action='store',
                        default=0,
                        type=float,
                        help='first point to consider as a ratio of the simulation box')
    parser.add_argument('--slice_end',
                        action='store',
                        default=1,
                        type=float,
                        help='last point to consider as a ratio of the simulation box')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    fdistribu = ds['fdistribu']
    density = compute_moment(fdistribu, 'v_x', moment_order=0)
    particle_flux = compute_moment(fdistribu, 'v_x', moment_order=1)
    data = compute_fluid_velocity(density, particle_flux)

    coord_x = data.coords['x'].values
    slice_left = coord_x[0] + args.slice_begin * (coord_x[-1] - coord_x[0])
    slice_right = coord_x[0] + args.slice_end * (coord_x[-1] - coord_x[0])
    time_init = fdistribu.coords['time'].values[0]
    time_diag = fdistribu.coords['time'].values[args.itime]

    for species in data.coords['species'].values:
        title = f'fluid velocity {species}'
        output_filename = Path.cwd() / f'fluid_velocity_{species}_xt.png'
        plot_field2d(data.sel(species=species),
                     title,
                     output_filename,
                     scale='linear',
                     cmap='viridis')

        output_filename = Path.cwd() / f'fluid_velocity_{species}_t{time_diag}.png'
        data_dict = {f't={time_init}': data.sel(time=time_init, species=species)[(coord_x <= slice_right) & (coord_x >= slice_left)],
                     f't={time_diag}': data.sel(time=time_diag, species=species)[(coord_x <= slice_right) & (coord_x >= slice_left)]}
        plot_field1d(data_dict, title, output_filename)
